-- Actualiza crédito de contactos importados desde el Excel original
-- Se ejecuta una sola vez via prisma migrate deploy

UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Agroindustrial Ferretera');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Axo Dominicana S.A.');
UPDATE contactos SET credito = 'DIAS_15' WHERE LOWER(nombre) = LOWER('Botes y Agregados Edwin E Ismael');
UPDATE contactos SET credito = 'DIAS_15' WHERE LOWER(nombre) = LOWER('Chiquito Agregado');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Corporacion Universal Del Caribe S.R.L');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Diconex');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Fesa S.R.L');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('I+D Consultoria de Mercado');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Industrias Bisono');
UPDATE contactos SET credito = 'DIAS_45' WHERE LOWER(nombre) = LOWER('Innova Centro');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Inversiones Arias Susana S.R.L');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Inversiones Obavenca');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('J. Electric Import SRL');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Jomsupli Ferroelectric');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('M & M World Plastic SRL');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Marcha EIRL');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Martur SRL.');
UPDATE contactos SET credito = 'DIAS_90' WHERE LOWER(nombre) = LOWER('Mercantil Del Caribe S.A.S');
UPDATE contactos SET credito = 'DIAS_45' WHERE LOWER(nombre) = LOWER('Mercaplas');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Morteros de Europa');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Osco Dominicana');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Petroquimicos automotrices SRL');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('ProContratista');
UPDATE contactos SET credito = 'DIAS_90' WHERE LOWER(nombre) = LOWER('R. Lopez e Hijos');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Ramón Corripio');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Resinas Dominicana, SRL');
UPDATE contactos SET credito = 'DIAS_90' WHERE LOWER(nombre) = LOWER('Soluciones HM');
UPDATE contactos SET credito = 'DIAS_45' WHERE LOWER(nombre) = LOWER('Valiente Fernandez SRL');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Wurth Dominicana, S.A.');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Alex Herrero');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ana Mena');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Andre La Roca');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Andres de la Rosa');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Angel Ciriaco');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Angel Valautre');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Arquimedez Jose');
UPDATE contactos SET credito = 'DIAS_10' WHERE LOWER(nombre) = LOWER('Auto Gala');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Balvuena Maestro');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Bandejor');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Basilia Jesus');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Benita');
UPDATE contactos SET credito = 'DIAS_15' WHERE LOWER(nombre) = LOWER('Candida Torres');
UPDATE contactos SET credito = 'DIAS_90' WHERE LOWER(nombre) = LOWER('Carabela');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Cariblu Proyecto');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Centro de Goma');
UPDATE contactos SET credito = 'DIAS_15' WHERE LOWER(nombre) = LOWER('Centro de Refrigeracion Rover');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Climalog');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Cristian');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Consultora Kolmen SRL');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Cristina Torres');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Disney Pujols');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Dra Berkis');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('El Pastor');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Emmanuel Perez');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Epedito');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Gina Figueroa');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Grupo Mayer');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ing Derick Rodriguez');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ing. Mendoza');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Inmobiliaria Mayer');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ivelice Tia De Sandra');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Jose Gerez');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Literal Construcciones');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Made Auto Import');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Malespin Constructora');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Maria La Barbie');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('R. Lopez e Hijos');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ramon Crisotomo');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ray Perez');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Ray Romulo');
UPDATE contactos SET credito = 'DIAS_60' WHERE LOWER(nombre) = LOWER('Universidad Psicologica Industrial');
UPDATE contactos SET credito = 'DIAS_30' WHERE LOWER(nombre) = LOWER('Filtrotech');
